var myselect = document.getElementById("club");
var autoList = [
    "SU Agen Lot-et-Garonne",
    "RC Arras",
    "SC Albi",
    "FC Auch Gers",
    "Stade Aurillac",
    "Stade Bagnérais",
    "Aviron Bayonnais",
    "CA Bordeaux-Bègles Gironde",
    "AS Béziers Hérault",
    "Biarritz Olympique",
    "Blagnac SCR",
    "AC Bobigny 93 Rugby",
    "Stade Bordelais",
    "Union Bordeaux Bègles",
    "CS Bourgoin-Jallieu",
    "US Bressane",
    "CA Brive",
    "US Carcassonne",
    "Cahors Rugby",
    "Castres Olympique",
    "RC Chalon",
    "SO Chambéry",
    "Châtenoy RC",
    "ASM Clermont Auvergne",
    "US Cognac",
    "Colomiers Rugby",
    "US Dax",
    "UA Gaillac",
    "SC Graulhet",
    "FC Grenoble",
    "Stade Rochelais",
    "ROC La Voulte-Valence",
    "CA Lannemezan",
    "Limoges Rugby",
    "FC Lourdes",
    "Lyon OU",
    "Olympique Marcquois Rugby",
    "Rugby Club Stade Phocéen",
    "RC Massy",
    "SC Mazamet",
    "US Montauban",
    "Montluçon Rugby",
    "Stade Montois",
    "Montpellier Hérault Rugby",
    "RC Narbonne",
    "USO Nevers",
    "RC Nîmes",
    "Stade Niortais",
    "RC Orléans",
    "Oyonnax Rugby",
    "Stade Français",
    "Racing 92",
    "Section Paloise",
    "CA Périgueux",
    "USA Perpignan",
    "Stade Poitevin Rugby",
    "Provence Rugby",
    "US Quillan",
    "Stade Rodez Aveyron",
    "Union Sportive Romanaise et Péageoise",
    "Football Club Sportif Rumilly",
    "ASC Saint Apollinaire",
    "CA Saint-Étienne",
    "Saint-Paul SR",
    "Soyaux Angoulême XV Charente",
    "Tarbes Pyrénées Rugby",
    "RC Toulonnais",
    "Stade Toulousain",
    "US Tours",
    "US Tyrosse",
    "Avenir Valencien",
    "Rugby Club Vannes",
    "RC Vichy",
    "SO Voiron"
];
for (let index = 0; index < autoList.length; index++) {
    const element = autoList[index];

    var option = document.createElement("option"); // Create a <li> node
    var textnode = document.createTextNode(element);
    var attribute = document.createAttribute("value");
    attribute.value = element;
    option.setAttributeNode(attribute);
    option.appendChild(textnode); // Append the text to <li>
    document.getElementById("club").appendChild(option); // Append <li> to <ul> with id="myList"

}